table 'Fact Team Needs'
	lineageTag: 70025919-535b-488e-b881-9232a5b4c574

	column team_id
		dataType: int64
		formatString: 0
		lineageTag: 8f783d53-f2d5-4443-8175-9110396578cf
		summarizeBy: none
		sourceColumn: team_id

		annotation SummarizationSetBy = Automatic

	column team_name
		dataType: string
		lineageTag: 4451d61e-cc7e-4c67-afca-46e251285aa7
		summarizeBy: none
		sourceColumn: team_name

		annotation SummarizationSetBy = Automatic

	column team_abbreviation
		dataType: string
		lineageTag: 960e5263-2c2d-4a96-840e-759cfad9b1d8
		summarizeBy: none
		sourceColumn: team_abbreviation

		annotation SummarizationSetBy = Automatic

	column league_name
		dataType: string
		lineageTag: bd644b3b-82f3-4097-9728-6f77d67a8ff8
		summarizeBy: none
		sourceColumn: league_name

		annotation SummarizationSetBy = Automatic

	column division_name
		dataType: string
		lineageTag: 06eeb71a-b582-494e-ba74-44afb1f02dfc
		summarizeBy: none
		sourceColumn: division_name

		annotation SummarizationSetBy = Automatic

	column wins
		dataType: int64
		formatString: 0
		lineageTag: ccc2a1a1-d25a-41ca-857d-4f27fd27a171
		summarizeBy: sum
		sourceColumn: wins

		annotation SummarizationSetBy = Automatic

	column losses
		dataType: int64
		formatString: 0
		lineageTag: b8feabb0-ab20-4ba9-9227-d23a20424e89
		summarizeBy: sum
		sourceColumn: losses

		annotation SummarizationSetBy = Automatic

	column winning_percentage
		dataType: double
		lineageTag: 795a9578-d3d6-47bc-89d6-b9105817d409
		summarizeBy: sum
		sourceColumn: winning_percentage

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column run_differential
		dataType: int64
		formatString: 0
		lineageTag: 9a31ccb8-2b59-4dd5-8e3f-3d1a8c153f55
		summarizeBy: sum
		sourceColumn: run_differential

		annotation SummarizationSetBy = Automatic

	column team_ops
		dataType: double
		lineageTag: 68b8408a-a41b-4c2a-bbd4-1f642d492607
		summarizeBy: sum
		sourceColumn: team_ops

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column runs_scored_per_game
		dataType: double
		lineageTag: 832b8fad-5594-4816-a3b0-c2ded6296830
		summarizeBy: sum
		sourceColumn: runs_scored_per_game

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column offensive_need_score
		dataType: double
		lineageTag: 624055b4-2351-496e-897b-a67a7d763dc3
		summarizeBy: sum
		sourceColumn: offensive_need_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column starter_innings_pitched
		dataType: double
		lineageTag: 15143ef2-fe59-46e8-b2cf-12b924f6edfb
		summarizeBy: sum
		sourceColumn: starter_innings_pitched

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column starter_era
		dataType: double
		lineageTag: 797dbe7b-bd9e-4693-be3b-1619773b0207
		summarizeBy: sum
		sourceColumn: starter_era

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column starter_whip
		dataType: double
		lineageTag: 7e9add00-0199-45e0-ab4a-6d5fa594eb00
		summarizeBy: sum
		sourceColumn: starter_whip

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column starter_k_per_nine
		dataType: double
		lineageTag: 5c5efcc6-5430-462e-87ec-844bd23af578
		summarizeBy: sum
		sourceColumn: starter_k_per_nine

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column starting_pitching_need_score
		dataType: double
		lineageTag: 298b0739-e0ee-4708-ab44-cca870a066bc
		summarizeBy: sum
		sourceColumn: starting_pitching_need_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column bullpen_innings_pitched
		dataType: double
		lineageTag: dd9ef507-d470-4674-abf2-b1263eaadf43
		summarizeBy: sum
		sourceColumn: bullpen_innings_pitched

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column bullpen_era
		dataType: double
		lineageTag: 651c3d51-2529-423c-9830-ef6af34f6f1a
		summarizeBy: sum
		sourceColumn: bullpen_era

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column bullpen_whip
		dataType: double
		lineageTag: 26c4019b-93f3-4aeb-a991-b0892d5d6f0c
		summarizeBy: sum
		sourceColumn: bullpen_whip

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column bullpen_k_per_nine
		dataType: double
		lineageTag: d41cd8ad-8c29-440d-8c52-90177300d9a8
		summarizeBy: sum
		sourceColumn: bullpen_k_per_nine

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column bullpen_need_score
		dataType: double
		lineageTag: c8d591a7-4715-4aed-8845-468983d2856d
		summarizeBy: sum
		sourceColumn: bullpen_need_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column overall_need_score
		dataType: double
		formatString: 0.00
		lineageTag: 8291a081-3cbf-4aaa-b847-ec2aab6430ac
		summarizeBy: sum
		sourceColumn: overall_need_score

		annotation SummarizationSetBy = Automatic

	column primary_need
		dataType: string
		lineageTag: 461d544e-9506-4949-aae5-6b9e81dbdc77
		summarizeBy: none
		sourceColumn: primary_need

		annotation SummarizationSetBy = Automatic

	column offensive_need_level
		dataType: string
		lineageTag: daa781e8-7038-4759-8a7a-491bd4530d4f
		summarizeBy: none
		sourceColumn: offensive_need_level

		annotation SummarizationSetBy = Automatic

	column starting_pitching_need_level
		dataType: string
		lineageTag: 4cf202de-272f-4b25-8cd3-51af94ffb572
		summarizeBy: none
		sourceColumn: starting_pitching_need_level

		annotation SummarizationSetBy = Automatic

	column bullpen_need_level
		dataType: string
		lineageTag: 6bf80439-8302-401b-a816-ac9e182b8a13
		summarizeBy: none
		sourceColumn: bullpen_need_level

		annotation SummarizationSetBy = Automatic

	column overall_need_level
		dataType: string
		lineageTag: 52e72238-01ed-40e0-829d-b8b3f3f3272d
		summarizeBy: none
		sourceColumn: overall_need_level

		annotation SummarizationSetBy = Automatic

	column season
		dataType: int64
		formatString: 0
		lineageTag: 4283274d-b580-454c-9aad-28157a2aca74
		summarizeBy: sum
		sourceColumn: season

		annotation SummarizationSetBy = Automatic

	column minimum_batting_plate_appearances
		dataType: int64
		formatString: 0
		lineageTag: 955a7023-220d-4060-b1ad-06fe3d5e9fdf
		summarizeBy: sum
		sourceColumn: minimum_batting_plate_appearances

		annotation SummarizationSetBy = Automatic

	column minimum_starter_games_started
		dataType: int64
		formatString: 0
		lineageTag: 25f30767-2d99-43aa-af6a-84e801875102
		summarizeBy: sum
		sourceColumn: minimum_starter_games_started

		annotation SummarizationSetBy = Automatic

	column minimum_starter_innings_pitched
		dataType: int64
		formatString: 0
		lineageTag: 27674f02-0db7-4059-98ce-ebf2c064b062
		summarizeBy: sum
		sourceColumn: minimum_starter_innings_pitched

		annotation SummarizationSetBy = Automatic

	column minimum_reliever_innings_pitched
		dataType: int64
		formatString: 0
		lineageTag: d853e80a-1a30-41fc-bec0-824d4b217fe2
		summarizeBy: sum
		sourceColumn: minimum_reliever_innings_pitched

		annotation SummarizationSetBy = Automatic

	column offensive_need_weight
		dataType: double
		lineageTag: 44d72e9c-a2cf-43a5-9f9b-a343d54d7cfb
		summarizeBy: sum
		sourceColumn: offensive_need_weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column starting_pitching_need_weight
		dataType: double
		lineageTag: 2856e729-390c-48d8-967e-e4863391e06f
		summarizeBy: sum
		sourceColumn: starting_pitching_need_weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column bullpen_need_weight
		dataType: double
		lineageTag: f50f7d01-c38c-43c9-a353-fac2a00f06ca
		summarizeBy: sum
		sourceColumn: bullpen_need_weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Fact Team Needs' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\mwhitney\OneDrive - ESI\Desktop\GitHubPersonal\MLB-Project\MLB-Front-Office-Manager\Data\Processed\fact_team_needs_2025.csv"),[Delimiter=",", Columns=36, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"team_id", Int64.Type}, {"team_name", type text}, {"team_abbreviation", type text}, {"league_name", type text}, {"division_name", type text}, {"wins", Int64.Type}, {"losses", Int64.Type}, {"winning_percentage", type number}, {"run_differential", Int64.Type}, {"team_ops", type number}, {"runs_scored_per_game", type number}, {"offensive_need_score", type number}, {"starter_innings_pitched", type number}, {"starter_era", type number}, {"starter_whip", type number}, {"starter_k_per_nine", type number}, {"starting_pitching_need_score", type number}, {"bullpen_innings_pitched", type number}, {"bullpen_era", type number}, {"bullpen_whip", type number}, {"bullpen_k_per_nine", type number}, {"bullpen_need_score", type number}, {"overall_need_score", type number}, {"primary_need", type text}, {"offensive_need_level", type text}, {"starting_pitching_need_level", type text}, {"bullpen_need_level", type text}, {"overall_need_level", type text}, {"season", Int64.Type}, {"minimum_batting_plate_appearances", Int64.Type}, {"minimum_starter_games_started", Int64.Type}, {"minimum_starter_innings_pitched", Int64.Type}, {"minimum_reliever_innings_pitched", Int64.Type}, {"offensive_need_weight", type number}, {"starting_pitching_need_weight", type number}, {"bullpen_need_weight", type number}})
				in
				    #"Changed Type"

	changedProperty = Name

	annotation PBI_ResultType = Table

